Natalie overall information card #4
nataliiazab/good-pr pull request #19
Opened 2023-06-21 20:16 UTC by nataliiazab

2023-06-21 22:44 UTC, momahboobian requested changes
Greate job Natalie 😊,
Perfect aproch on functionalties. I have left a few comments, please review and make the neccarly changes.
Thanks an well done 👍🏻

2023-06-21 22:44 UTC, momahboobian commented on src/app/components/OverallInfoCard.js
> +                data.issues.filter((issue) => issue.state == "done").length
In here you should look for "closed" instead of "done"

2023-06-21 22:44 UTC, momahboobian commented on src/app/components/OverallInfoCard.js
> +        <button className="bg-[#111827] text-[#F9F9F9]">...</button>
It shouldn't be any bg color for "..."

2023-06-21 22:44 UTC, momahboobian commented on src/app/components/OverallInfoCard.js
> +            <p className="text-xs mt-2">Tasks</p>
Font color should be balck accouring to wireframe,
Also you need to amend the color for In progress and Completed.
On thing that I have notice inside the text and icons are not exactly cerntered. So worth to have a look when had chance.

2023-06-22 07:43 UTC, nataliiazab commented on src/app/components/OverallInfoCard.js
> +        <button className="bg-[#111827] text-[#F9F9F9]">...</button>
What do you mean?

2023-06-22 07:47 UTC, momahboobian commented on src/app/components/OverallInfoCard.js
> +        <button className="bg-[#111827] text-[#F9F9F9]">...</button>
I meant this, bg-[#111827]
For 3 dots menu, there is background color where we don’t need.
Sorry if I was too picky. It’s just a small style issue 😊.

2023-06-22 07:55 UTC, nataliiazab commented on src/app/components/OverallInfoCard.js
> +        <button className="bg-[#111827] text-[#F9F9F9]">...</button>
got it now:) That's alright, I appreciate you having a look!

2023-06-22 08:01 UTC, nataliiazab commented on src/app/components/OverallInfoCard.js
> +            <p className="text-xs mt-2">Tasks</p>
THAnks for catching this! changed it now - please review and merge if okay :)

2023-06-22 10:58 UTC, momahboobian requested changes
Well done @nataliiazab,
I can see you haven't replace the "done" to "closed" in order to calculate the status of issue, (line 14) I have left comment yesterday.

Also, sorry, I should have be more specific about the text-color contnent inside each (TASKS, In Progress and Completed), I have assumed you would look at the wireframe, Their color are black.
You have need to change the color for all text and icones inside the these threr small cards.
 Please see the and compare the screenshots bellow 😊
<img width="534" alt="Screenshot 2023-06-22 at 11 52 42"
 src="https://github.com/nataliiazab/good-pr/assets/17272675/b5a0811f-afe4-4802-8d5b-06a11e2af743">
<img width="555" alt="Screenshot 2023-06-22 at 11 54 18" src="https://github.com/nataliiazab/good-pr/assets/17272675/b2be9648-7888-437b-8e85-187faed7ffe8">

2023-06-22 11:07 UTC, nataliiazab commented
@momahboobian, I did according with the template and it is black on my side. Please check if you applied your own classes to the main page

![Screenshot from 2023-06-22 12-06-13](https://github.com/nataliiazab/good-pr/assets/113237479/d0d2a2a2-33ca-4159-b9b8-996a24e7468c)

2023-06-22 11:51 UTC, momahboobian approved these changes
All good thank you so much 😊

2023-06-22 11:51 UTC, merged